### ISSUE TITLE
Rozdzielić ui menadżera sieci i menadżera restauracji

### ISSUE THREAD

**Issue by Kadek** [Kadek/ProjektowanieOprogramowania#10]
Folder employee kopiujesz i oryginał nazywasz ui_menadzera_sieci a kopię ui_menadzera_restauracji. To mają być dwa oddzielne strony internetowe. employee usuwasz.

Odpal oba i sprawdź czy działają, po prostu czy się włączają.

**Comment by chernenv** [comment]
Działają
