### ISSUE TITLE
Dodać diagramy klas dla frontu

### ISSUE THREAD

**Issue by Kadek** [Kadek/ProjektowanieOprogramowania#13]
NAJPIERW NAPISZ KOD!

potem sprawdź czy są narzędzia do generowanie diagramu dla angulara i ich uzyj. Jeśli takich nie ma to zrób te diagramy ręcznie ale bez atrybutów (na wzór tych moich ale ze strzałkami).

**Comment by chernenv** [comment]
Mam, napisałem do Pawła, jak nie odpisze - wsadzam tutaj.
