### ISSUE TITLE
Komunikacja z uzytkownikiem

### ISSUE THREAD

**Issue by Kadek** [Kadek/ProjektowanieOprogramowania#18]
Po kliknięciu przycisku powinien w dodawanie pracownika, dodawanie restauracji, dodawanie ogłoszenia pojawić się komunikat z wiadomością otrzymaną od serwera.

**Comment by chernenv** [comment]
![image](https://user-images.githubusercontent.com/18377151/49327446-26b81b00-f562-11e8-8c5d-52701dd1fc39.png)

**Comment by chernenv** [comment]
![image](https://user-images.githubusercontent.com/18377151/49327728-063d9000-f565-11e8-9a14-f9566951b648.png)
![image](https://user-images.githubusercontent.com/18377151/49327729-0dfd3480-f565-11e8-90c5-b4e2f03ad82d.png)
![image](https://user-images.githubusercontent.com/18377151/49327731-19e8f680-f565-11e8-9e1c-9637c0cbd4fd.png)
Na każdym działa
