### ISSUE TITLE
Wyświetlenie listy restauracji

### ISSUE THREAD

**Issue by Kadek** [Kadek/ProjektowanieOprogramowania#26]
W ui-menadżera-sieci zakładkę dodanie restauracji zamieniasz na zarządzanie restauracją.

Strona oprócz formularza powinna mieć też listę restauracji. Układ strony taki sam jak z ogłoszeniami o pracowników. Jak lista ma wyglądać masz wypisane w scenopisie.

O listę restauracji odpytujesz localhost:9094/pobierz_restauracje . I dostajesz listę obiektów o polach: id_restauracji, nazwa, lokalizacja, menadzer.

**Comment by Kadek** [comment]
Back end gotowy, trzebą połączyć.

**Comment by chernenv** [comment]
Pobieram restauracje, ale nie dostaje menadżera w tym. Co robić?

**Comment by Kadek** [comment]
http://localhost:9090/pobierz_menadzerow i  zwraca Ci piękną listę menadzerów, którymi uzupełniasz listę restauracji

**Comment by Kadek** [comment]
Gdy restauracja nie ma managera, to powinno się wyświetlać "Brak"

**Comment by chernenv** [comment]
Zrobione
