### ISSUE TITLE
Wyświetl listę pracowników

### ISSUE THREAD

**Issue by Kadek** [Kadek/ProjektowanieOprogramowania#30]
W ui-menadżera-sieci oraz ui-menadzera-restauracji zakładkę dodanie pracownika zamieniasz na zarządzanie pracownikami.

Strona oprócz formularza powinna mieć też listę pracowników. Układ strony taki sam jak z ogłoszeniami o pracowników. Jak lista ma wyglądać masz wypisane w scenopisie.

O listę pracowników odpytujesz localhost:9090/pobierz_pracownikow . I dostajesz listę pracowników.

**Comment by Kadek** [comment]
Potrzebny tutorial z używania sesji

**Comment by Kadek** [comment]
Na razie wszystko robimy na wszystkich pracownikach póki się nie ogarnie logowania.

**Comment by chernenv** [comment]
Mamy ogolnie pracowników oraz pracowników w restauracji więc chyba zamykam
