### ISSUE TITLE
Zwolnienie pracownika

### ISSUE THREAD

**Issue by Kadek** [Kadek/ProjektowanieOprogramowania#31]
W ui-menadżera-sieci oraz ui-menadzera-restauracji zakładkę dodanie pracownika zamieniasz na zarządzanie pracownikami.

Strona oprócz formularza powinna mieć też listę pracowników. Układ strony taki sam jak z ogłoszeniami o pracowników. Jak lista ma wyglądać masz wypisane w scenopisie.

Po kliknięciu na ikonkę X przy jednym z pracowników wyświetla się okienko z pytaniem "Czy na pewno chcesz zwolnić tego pracownika?" i przyciskami "Tak", "Nie". Po kliknięciu "Nie" zamykasz okno. Po kliknięciu "Tak" zamykasz okno, wysyłasz GET'a na localhost:9090/usun_pracownika z atrybutem id_pracownika. a potem GET'a na localhost:9090/pobierz_pracownikow i wyświetlasz zaktualizowaną listę pracownikow.

**Comment by Kadek** [comment]
Back end gotowy, trzeba tylko podpiąć i zdebuggować.

**Comment by chernenv** [comment]
Działa
