### ISSUE TITLE
Scenopisy obrazki

### ISSUE THREAD

**Issue by Kadek** [Kadek/ProjektowanieOprogramowania#32]
Potrzebne sa projekty GUI do scenopisów.

Przejdź po każdym przypadku użycia i potwórz wszystkie elementy graficzne jakie tam są wymieniane. Szkice wstaw na google drive i ja to potem wkleję w scenopisy

**Comment by chernenv** [comment]
Zrobione oraz wstawiłem na google drive, ale sprawdź na wszelki wypadek
