### ISSUE TITLE
Uprzyjaźnić dla użytkownika

### ISSUE THREAD

**Issue by Kadek** [Kadek/ProjektowanieOprogramowania#36]
W ui-menadzer-sieci i ui-menadzera-restauracji

W dodawaniu pracownika: hasło powinno być polem password

W dodawaniu pracownika/ogłoszenia/restauracji: wstępna walidacja inputów, (tutaj masz specyfikacje [spec](https://dev.azure.com/279054/PO%20Sie%C4%87%20Restauracji/_wiki/wikis/PO-Sie%C4%87-Restauracji.wiki?wikiVersion=GBwikiMaster&pagePath=%2FProjekt%20systemu%2FS%C5%82ownik%20%252D%20Model%20danych%20%252D%20Walidacja) ), tzn. gdy coś jest wpisywane to powinno się pojawić małe info, jeśli jest źle

**Comment by chernenv** [comment]
Dodałem
